omr:
  pdf_dpi: 300
  preprocessing_kernel_size: [5, 5]
  staff_line_detection_threshold: 0.7
  symbol_recognition_confidence: 0.8 # Prioritized from supersmm_config.yaml (was 0.7 in old config.yml)

  # The following preprocessing settings are from your existing config.yml.
  # NOTE: These are not currently used by the OMRPipeline's OMRSettings dataclass.
  # To use them, the OMRSettings dataclass and ConfigManager would need to be updated.
  # min_image_size: [100, 100]
  # max_image_size: [5000, 5000]
  # color_mode: 'rgb'
  # preprocessing_methods:
  #   - 'grayscale'
  #   - 'normalize'
  #   - 'denoise'

segmentation: # Settings for SymbolSegmenter, from your existing config.yml
  min_symbol_size: 10
  max_symbol_size: 500
  segmentation_strategy: 'connected_components'
  confidence_threshold: 0.5

  # The following recognition setting is from your existing config.yml.
  # NOTE: This is not currently used by the OMRPipeline's OMRSettings or MLModelSettings.
  # top_k_predictions: 3

export:
  output_directory: /ml/models/resources/tf-deep-omr/exports
  export_format: musicxml

ml_models:
  symbol_recognition_model_path: /ml/models/resources/tf-deep-omr/resources/ml_models/symbol_recognition/best_model.h5
  training_data_dir: /ml/models/resources/tf-deep-omr/resources/training_data/music_symbols
  vocabulary_path: /ml/models/resources/tf-deep-omr/Data/vocabulary_semantic.txt