# Training configuration for the CTC model

# Data parameters - using relative paths from project root
corpus: ./src/Data/primus
set_file: ./src/Data/train.txt
vocabulary: ./src/Data/vocabulary_semantic.txt
semantic: true
agnostic: false
validation_split: 0.1

# Model parameters
img_height: 128
dropout: 0.5
img_channels: 1  # Grayscale images
conv_blocks: 5   # Number of convolutional blocks
conv_pooling_size: [2, 2, 2, 2, 1]  # Pooling size for each block

# Training parameters
epochs: 50
batch_size: 50
learning_rate: 0.001
save_model: ./models/Semantic-Model
restore: false  # Whether to restore from checkpoint
early_stopping: 10  # Stop if no improvement for N epochs

# Data augmentation
augment: true
max_rotation: 5  # degrees
max_scale: 0.1   # +- 10% scale
max_translation: 10  # pixels

# Learning rate scheduling
lr_decay: 0.9    # Learning rate decay factor
lr_patience: 5   # Epochs before reducing LR
min_lr: 1e-5     # Minimum learning rate

# Validation parameters
validate_every: 50  # Validate every N batches
validation_steps: 20 # Number of batches to use for validation

# Logging and checkpoints
log_dir: ./logs
checkpoint_dir: ./model/primus_model
save_checkpoints: true
checkpoint_frequency: 50  # Save checkpoint every N batches

# Hardware
device: /gpu:0  # or /cpu:0
allow_growth: true  # Allow GPU memory growth

# Debugging
debug: false
log_level: INFO  # DEBUG, INFO, WARNING, ERROR
